DROP TABLE IF EXISTS "to_calls";
CREATE TABLE "public"."to_calls" (
    "callsign" character(6) NOT NULL,
    "description" character varying(255) NOT NULL,
    CONSTRAINT "to_calls_callsign" PRIMARY KEY ("callsign")
) WITH (oids = false);

INSERT INTO "to_calls" ("callsign", "description") VALUES
('AP****',	'Unknown Equipment'),
('AP1WWX',	'TAPR T-238+ WX station'),
('AP1MAJ',	'Martyn M1MAJ DeLorme inReach Tracker'),
('AP4R**',	'APRS4R software interface'),
('AP***D',	'Painter Engineering uSmartDigi D-Gate DSTAR Gateway'),
('AP***U',	'Painter Engineering uSmartDigi Digipeater'),
('APAF**',	'Afilter'),
('APAG**',	'AGATE'),
('APAGW*',	'SV2AGW''s AGWtracker'),
('APAL**',	'Alinco DR-620/635 internal TNC digis. "Hachi" ,JF1AJE'),
('APAX**',	'AFilterX'),
('APAH**',	'AHub'),
('APAND1',	'APRSdroid (pre-release) http://aprsdroid.org/'),
('APAM**',	'Altus Metrum GPS trackers'),
('APATAR',	'ATA-R APRS Digipeater by TA7W/OH2UDS and TA6AEU'),
('APAVT5',	'SainSonic AP510 which is a 1watt tracker'),
('APAW**',	'AGWPE'),
('APB***',	'Beacons or Rabbit TCPIP micros?'),
('APB2MF',	'DL2MF - MF2APRS Radiosonde for balloons'),
('APBL**',	'BigRedBee BeeLine'),
('APBLO ',	'MOdel Rocketry K7RKT'),
('APBK**',	'PY5BK Bravo Tracker in Brazil'),
('APBPQ*',	'John G8BPQ Digipeater/IGate'),
('APBM**',	'BrandMeister DMR Server for R3ABM'),
('APBSD*',	'HamBSD https://hambsd.org/'),
('APBT62',	'BTech DMR 6x2'),
('APC***',	'Cellular Applications'),
('APCBB*',	'VE7UDP Blackberry Applications'),
('APCDS0',	'Leon Lessing ZS6LMG''s cell tracker'),
('APCLEY',	'EYTraker GPRS/GSM tracker by ZS6EY'),
('APCLEZ',	'Telit EZ10 GSM application ZS6CEY'),
('APCLUB',	'Brazil APRS network'),
('APCLWX',	'EYWeather GPRS/GSM WX station by ZS6EY'),
('APCN**',	'for carNET by DG5OAW'),
('APCSMS',	'for Cosmos (used for sending commands @USNA)'),
('APCSS ',	'for AMSAT cubesats https://cubesatsim.org'),
('APCWP8',	'John GM7HHB, WinphoneAPRS'),
('APCY**',	'Cybiko applications'),
('APD4**',	'UP4DAR platform'),
('APDD**',	'DV-RPTR Modem and Control Center Software'),
('APDF**',	'Automatic DF units'),
('APDG**',	'D-Star Gateways by G4KLX ircDDB'),
('APDH**',	'WinDV (DUTCH*Star DV Node for Windows)'),
('APDI**',	'DIXPRS - Bela, HA5DI'),
('APDIGI',	'Used by PSAT2 to indicate the digi is ON'),
('APDK**',	'KI4LKF g2_ircddb Dstar gateway software'),
('APDNO*',	'APRSduino by DO3SWW'),
('APDO**',	'ON8JL Standalone DStar Node'),
('APDPRS',	'D-Star originated posits'),
('APDR**',	'APRSdroid Android App http://aprsdroid.org/'),
('APDSXX',	'SP9UOB for dsDigi and ds-tracker'),
('APDT**',	'APRStouch Tone (DTMF)'),
('APDTMF',	'digi off mode on QIKCOM2 and DTMF ON'),
('APDU**',	'U2APRS by JA7UDE'),
('APDV**',	'OE6PLD''s SSTV with APRS status exchange'),
('APDW**',	'DireWolf, WB2OSZ'),
('APE***',	'Telemetry devices'),
('APE2A*',	'VA3NNW''s Email-2-APRS ap'),
('APECAN',	'Pecan Pico APRS Balloon Tracker'),
('APELK*',	'WB8ELK balloons'),
('APERXQ',	'Experimental tracker by PE1RXQ'),
('APERS*',	'Runner tracking by Jason,KG7YKZ'),
('APESPG',	'ESP SmartBeacon APRS-IS Client'),
('APESPW',	'ESP Weather Station APRS-IS Client'),
('APF***',	'Firenet'),
('APFG**',	'Flood Gage (KP4DJT)'),
('APFI**',	'for APRS.FI OH7LZB, Hessu'),
('APFPRS',	'for FreeDV by Jeroen PE1RXQ'),
('APG***',	'Gates, etc'),
('APGO**',	'for AA3NJ PDA application'),
('APGBLN',	'for NW5W''s GoBalloon'),
('APGDT*',	'for VK4FAST''s Graphic Data Terminal'),
('APHK**',	'for LA1BR tracker/digipeater'),
('APHAX*',	'SM2APRS by PY2UEP'),
('APHBL*',	'for DMR Gateway by Eric - KF7EEL'),
('APHT**',	'HMTracker by IU0AAC'),
('APHW**',	'for use in "HamWAN'),
('API282',	'for ICOM IC-2820'),
('API31 ',	'for ICOM ID-31'),
('API410',	'for ICOM ID-4100'),
('API51 ',	'for ICOM ID-51'),
('API510',	'for ICOM ID-5100'),
('API710',	'for ICOM IC-7100'),
('API80 ',	'for ICOM IC-80'),
('API880',	'for ICOM ID-880'),
('API910',	'for ICOM IC-9100'),
('API92 ',	'for ICOM IC-92'),
('API970',	'for ICOM 9700'),
('APICQ*',	'for ICQ'),
('APIC**',	'HA9MCQ''s Pic IGate'),
('APIE**',	'W7KMV''s PiAPRS system'),
('APIN**',	'PinPoint by AB0WV'),
('APIZCI',	'hymTR IZCI Tracker by TA7W/OH2UDS and TA6AEU'),
('APJ8**',	'Jordan / KN4CRD JS8Call application'),
('APJA**',	'JavAPRS'),
('APJE**',	'JeAPRS'),
('APJI**',	'jAPRSIgate'),
('APJS**',	'javAPRSSrvr'),
('APJY**',	'KA2DDO Yet another APRS system'),
('APK0**',	'Kenwood TH-D7''s'),
('APK003',	'Kenwood TH-D72'),
('APK004',	'Kenwood TH-D74'),
('APK1**',	'Kenwood D700''s'),
('APK102',	'Kenwood D710'),
('APKRAM',	'KRAMstuff.com - Mark. G7LEU'),
('APLC**',	'APRScube by DL3DCW'),
('APLG**',	'LoRa Gateway/Digipeater OE5BPA'),
('APLIG*',	'LightAPRS - TA2MUN and TA9OHC'),
('APLO**',	'LoRa KISS TNC/Tracker'),
('APLQRU',	'Charlie - QRU Server'),
('APLM**',	'WA0TQG transceiver controller'),
('APLS**',	'SARIMESH  ( http://www.sarimesh.net )'),
('APLT**',	'LoRa Tracker - OE5BPA'),
('APM***',	'MacAPRS,'),
('APMG**',	'PiCrumbs and MiniGate - Alex, AB0TJ'),
('APMI**',	'SQ3PLX http://microsat.com.pl/'),
('APMPAD',	'DF1JSL''s WXBot clone and extension'),
('APMQ**',	'Ham Radio of Things WB2OSZ'),
('APMT**',	'LZ1PPL for tracker'),
('APN***',	'Network nodes, digis, etc'),
('APN2**',	'NOSaprs for JNOS 2.0 - VE4KLM'),
('APN3**',	'Kantronics KPC-3 rom versions'),
('APN9**',	'Kantronics KPC-9612 Roms'),
('APNA**',	'WB6ZSU''s APRServe'),
('APND**',	'DIGI_NED'),
('APAT51',	'Anytone AT-D578UV APRS mobile radio'),
('APAT8*',	'Anytone DMR HT'),
('APNIC*',	'SQ5EKU http://sq5eku.blogspot.com/'),
('APNK01',	'Kenwood D700 (APK101) type'),
('APNK80',	'KAM version 8.0'),
('APNKMP',	'KAM+'),
('APNKMX',	'KAM-XL'),
('APNM**',	'MJF TNC roms'),
('APNP**',	'Paccom TNC roms'),
('APNT**',	'SV2AGW''s TNT tnc as a digi'),
('APNU**',	'UIdigi'),
('APNV**',	'SQ8L''s VP digi and Nodes'),
('APNX**',	'TNC-X  (K6DBG)'),
('APNW**',	'SQ3FYK.com WX/Digi and SQ3PLX http://microsat.com.pl/'),
('APRS**',	'Unknown APRS Server'),
('APOFF ',	'Used by PSAT and PSAT2 to indicate the digi is OFF'),
('APOLU*',	'for OSCAR satellites for AMSAT-LU by LU9DO'),
('APOA**',	'OpenAPRS - Greg Carter'),
('APOCSG',	'For N0AGI''s APRS to POCSAG project'),
('APOD1w',	'Open Track with 1 wire WX'),
('APOSB*',	'openSPOT3 by HA2NON at sharkrf.com'),
('APOSW*',	'openSPOT2'),
('APOT**',	'Open Track'),
('APOU2k',	'Open Track for Ultimeter'),
('APOZ**',	'www.KissOZ.dk Tracker. OZ1EKD and OZ7HVO'),
('APP6**',	'for APRSlib'),
('APPIC*',	'DB1NTO'' PicoAPRS'),
('APPM**',	'DL1MX''s RTL-SDR pytohon Igate'),
('APPT**',	'KetaiTracker by  JF6LZE, Takeki (msg capable)'),
('APQ***',	'Earthquake data'),
('APQTH*',	'W8WJB''s QTH.app'),
('APR8**',	'APRSdos versions 800+'),
('APR2MF',	'DL2MF - MF2APRS Radiosonde WX reporting'),
('APRARX',	'VK5QI''s radiosonde tracking'),
('APRD**',	'APRSdata, APRSdr'),
('APRG**',	'aprsg igate software, OH2GVE'),
('APRHH2',	'HamHud 2'),
('APRK**',	'APRStk'),
('APRNOW',	'W5GGW ipad application'),
('APRRT*',	'RPC electronics'),
('APRS  ',	'Generic, (obsolete. Digis should use APNxxx instead)'),
('APRSON',	'Used by PSAT to indicate the DIGI is ON'),
('APRX00',	'OH2MQK iGate'),
('APRX01',	'OH2MQK iGate'),
('APRX02',	'OH2MQK iGate'),
('APRX03',	'OH2MQK iGate'),
('APRX04',	'OH2MQK iGate'),
('APRX05',	'OH2MQK iGate'),
('APRX06',	'OH2MQK iGate'),
('APRX07',	'OH2MQK iGate'),
('APRX08',	'OH2MQK iGate'),
('APRX09',	'OH2MQK iGate'),
('APRX10',	'OH2MQK iGate'),
('APRX11',	'OH2MQK iGate'),
('APRX12',	'OH2MQK iGate'),
('APRX13',	'OH2MQK iGate'),
('APRX14',	'OH2MQK iGate'),
('APRX15',	'OH2MQK iGate'),
('APRX16',	'OH2MQK iGate'),
('APRX17',	'OH2MQK iGate'),
('APRX18',	'OH2MQK iGate'),
('APRX19',	'OH2MQK iGate'),
('APRX20',	'OH2MQK iGate'),
('APRX21',	'OH2MQK iGate'),
('APRX22',	'OH2MQK iGate'),
('APRX23',	'OH2MQK iGate'),
('APRX24',	'OH2MQK iGate'),
('APRX25',	'OH2MQK iGate'),
('APRX26',	'OH2MQK iGate'),
('APRX27',	'OH2MQK iGate'),
('APRX28',	'OH2MQK iGate'),
('APRX29',	'OH2MQK iGate'),
('APRX30',	'OH2MQK iGate'),
('APRX31',	'OH2MQK iGate'),
('APRX32',	'OH2MQK iGate'),
('APRX33',	'OH2MQK iGate'),
('APRX34',	'OH2MQK iGate'),
('APRX35',	'OH2MQK iGate'),
('APRX36',	'OH2MQK iGate'),
('APRX37',	'OH2MQK iGate'),
('APRX38',	'OH2MQK iGate'),
('APRX41',	'APRSmax'),
('APRX42',	'APRSmax'),
('APRX43',	'APRSmax'),
('APRX44',	'APRSmax'),
('APRX45',	'APRSmax'),
('APRX46',	'APRSmax'),
('APRX47',	'APRSmax'),
('APRX48',	'APRSmax'),
('APRX49',	'APRSmax'),
('APRX50',	'APRSmax'),
('APRX51',	'APRSmax'),
('APRX52',	'APRSmax'),
('APRX53',	'APRSmax'),
('APRX54',	'APRSmax'),
('APRX55',	'APRSmax'),
('APRX56',	'APRSmax'),
('APRX57',	'APRSmax'),
('APRX58',	'APRSmax'),
('APRX59',	'APRSmax'),
('APRX60',	'APRSmax'),
('APRX61',	'APRSmax'),
('APRX62',	'APRSmax'),
('APRX63',	'APRSmax'),
('APRX64',	'APRSmax'),
('APRX65',	'APRSmax'),
('APRX66',	'APRSmax'),
('APRX67',	'APRSmax'),
('APRX68',	'APRSmax'),
('APRX69',	'APRSmax'),
('APRX70',	'APRSmax'),
('APRX71',	'APRSmax'),
('APRX72',	'APRSmax'),
('APRX73',	'APRSmax'),
('APRX74',	'APRSmax'),
('APRX75',	'APRSmax'),
('APRX76',	'APRSmax'),
('APRX77',	'APRSmax'),
('APRX78',	'APRSmax'),
('APRX79',	'APRSmax'),
('APRX80',	'APRSmax'),
('APRX81',	'APRSmax'),
('APRX82',	'APRSmax'),
('APRX83',	'APRSmax'),
('APRX84',	'APRSmax'),
('APRX85',	'APRSmax'),
('APRX86',	'APRSmax'),
('APRX87',	'APRSmax'),
('APRX88',	'APRSmax'),
('APRX89',	'APRSmax'),
('APRX90',	'APRSmax'),
('APRX91',	'APRSmax'),
('APRX92',	'APRSmax'),
('APRX93',	'APRSmax'),
('APRX94',	'APRSmax'),
('APRX95',	'APRSmax'),
('APRX96',	'APRSmax'),
('APRX97',	'APRSmax'),
('APRX98',	'APRSmax'),
('APRX99',	'APRSmax'),
('APRTLM',	'used in MIM''s and Mic-lites, etc'),
('APRtfc',	'APRStraffic'),
('APRST*',	'APRStt (Touch tone)'),
('APS***',	'APRS+SA, etc'),
('APSAR*',	'ZL4FOX''s SARTRACK'),
('APSAT ',	'digi ON for QIKCOM-1'),
('APSC**',	'aprsc APRS-IS core server (OH7LZB, OH2MQK)'),
('APSF**',	'F5OPV embedded devices - was APZ40'),
('APSK63',	'APRS Messenger -over-PSK63'),
('APSK25',	'APRS Messenger GMSK-250'),
('APSMS*',	'Paul Dufresne''s SMSGTE - SMS Gateway'),
('APSTM*',	'for W7QO''s Balloon trackers'),
('APSTPO',	'for N0AGI Satellite Tracking and Operations'),
('APT2**',	'Tiny Track II'),
('APT3**',	'Tiny Track III'),
('APTA**',	'K4ATM''s tiny track'),
('APTB**',	'TinyAPRS by BG5HHP Was APTAxx till Sep 2017'),
('APTCHE',	'PU3IKE in Brazil TcheTracker/Tcheduino'),
('APTCMA',	'CAPI tracker - PU1CMA Brazil'),
('APTIGR',	'TigerTrack'),
('APTKPT',	'TrackPoint N0LP'),
('APTPN*',	'TARPN Packet Node Tracker by KN4ORB http://tarpn.net/'),
('APTT**',	'Tiny Track'),
('APTW**',	'Byons WXTrac'),
('APTV**',	'for ATV/APRN and SSTV applications'),
('APU1**',	'UIview 16 bit applications'),
('APU2**',	'UIview 32 bit apps'),
('APU3**',	'UIview terminal program'),
('APUDR*',	'NW Digital Radio''s UDR (APRS/Dstar)'),
('APV***',	'Voice over Internet  applications'),
('APVM**',	'DRCC-DVM Digital Voice (Digital Radio China Club)'),
('APVR**',	'for IRLP'),
('APVL**',	'for I-LINK'),
('APVE**',	'for ECHO link'),
('APW***',	'WinAPRS, etc'),
('APW9**',	'9A9Y Weather Tracker'),
('APWA**',	'APRSISCE Android version'),
('APWS**',	'DF4IAN''s WS2300 WX station'),
('APWM**',	'APRSISCE KJ4ERJ'),
('APWW**',	'APRSISCE win32 version'),
('APX***',	'Xastir'),
('APXR**',	'Xrouter'),
('APY***',	'Yaesu Radios'),
('APY008',	'Yaesu VX-8 series'),
('APY01D',	'Yaesu FT1D series'),
('APY02D',	'Yaesu FT2D series'),
('APY03D',	'Yaesu FT3D series'),
('APY05D',	'Yaesu FT5D series'),
('APY100',	'Yaesu FTM-100D series'),
('APY300',	'Yaesu FTM-300D series'),
('APY350',	'Yaesu FTM-350  series'),
('APY400',	'Yaesu FTM-400D series'),
('APZ***',	'Experimental'),
('APZ200',	'old versions of JNOS'),
('APZ247',	'for UPRS NR0Q'),
('APZ0**',	'Xastir (old versions. See APX)'),
('APZMAJ',	'Martyn M1MAJ DeLorme inReach Tracker'),
('APZMDR',	'for HaMDR trackers - hessu * hes.iki.fi]'),
('APZPAD',	'Smart Palm'),
('APZTKP',	'TrackPoint, Nick N0LP (Balloon tracking)(depricated)'),
('APZWIT',	'MAP27 radio (Mountain Rescue) EI7IG'),
('APZWKR',	'GM1WKR NetSked application'),
('APAT81',	'Anytone 868/878uv HT');
